name: Release Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish Snapshot
        run: ./gradlew -Prelease.useLastTag=true -Pbintray.user=${{ secrets.BINTRAY_USER }} -Pbintray.key=${{ secrets.BINTRAY_KEY }} final
